version: '3.8'

services:

#   dind-test2:
#     image: docker:dind
#     privileged: true
#     volumes:
#       - ../Docking:/flask_app
#     ports:
#       - "5000:5000"

  flask-app:
    build: 
      context: ./flask_app
      dockerfile: Dockerfile
    volumes:
      - ./flask_app:/app
    ports:
      - "5000:5000"

  # mtconnect-agent-1:
  #   image: mtconnect/agent:latest
  #   volumes:
  #     - ./agents/mc1/config:/mtconnect/config
  #     - ./agents/mc1/log:/mtconnect/log
  #     - ./agents/shared:/mtconnect/data
  #   ports:
  #     - "5001:5000"

  # mtconnect-agent-2:
  #   image: mtconnect/agent:latest
  #   volumes:
  #     - ./agents/mc2/config:/mtconnect/config
  #     - ./agents/mc2/log:/mtconnect/log
  #     - ./agents/shared:/mtconnect/data
  #   ports:
  #     - "5002:5000"

  # mtconnect-agent-3:
  #   image: mtconnect/agent:latest
  #   volumes:
  #     - ./agents/mc3/config:/mtconnect/config
  #     - ./agents/mc3/log:/mtconnect/log
  #     - ./agents/shared:/mtconnect/data
  #   ports:
  #     - "5003:5000"

  # mtconnect-agent-4:
  #   image: mtconnect/agent:latest
  #   volumes:
  #     - ./agents/mc4/config:/mtconnect/config
  #     - ./agents/mc4/log:/mtconnect/log
  #     - ./agents/shared:/mtconnect/data
  #   ports:
  #     - "5004:5000"

  # mtconnect-agent-5:
  #   image: mtconnect/agent:latest
  #   volumes:
  #     - ./agents/mc5/config:/mtconnect/config
  #     - ./agents/mc5/log:/mtconnect/log
  #     - ./agents/shared:/mtconnect/data
  #   ports:
  #     - "5005:5000"

  # mtconnect-agent-6:
  #   image: mtconnect/agent:latest
  #   volumes:
  #     - ./agents/mc6/config:/mtconnect/config
  #     - ./agents/mc6/log:/mtconnect/log
  #     - ./agents/shared:/mtconnect/data
  #   ports:
  #     - "5006:5000"

  # mtconnect-agent-7:
  #   image: mtconnect/agent:latest
  #   volumes:
  #     - ./agents/mc7/config:/mtconnect/config
  #     - ./agents/mc7/log:/mtconnect/log
  #     - ./agents/shared:/mtconnect/data
  #   ports:
  #     - "5007:5000"

  # mtconnect-agent-8:
  #   image: mtconnect/agent:latest
  #   volumes:
  #     - ./agents/mc8/config:/mtconnect/config
  #     - ./agents/mc8/log:/mtconnect/log
  #     - ./agents/shared:/mtconnect/data
  #   ports:
  #     - "5008:5000"

  # mtconnect-agent-9:
  #   image: mtconnect/agent:latest
  #   volumes:
  #     - ./agents/mc9/config:/mtconnect/config
  #     - ./agents/mc9/log:/mtconnect/log
  #     - ./agents/shared:/mtconnect/data
  #   ports:
  #     - "5009:5000"

  # mtconnect-agent-10:
  #   image: mtconnect/agent:latest
  #   volumes:
  #     - ./agents/mc10/config:/mtconnect/config
  #     - ./agents/mc10/log:/mtconnect/log
  #     - ./agents/shared:/mtconnect/data
  #   ports:
  #     - "5010:5000"