version: '3.8'

services:
  # dind-test2:
  #   image: docker:dind
  #   privileged: true
  #   volumes:
  #     - ../Docking:/flask_app
  #   ports:
  #     - "5000:5000"
  
  flask-app:
    build: 
      context: ./
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: C:\Users\momoore\Documents\smartbox-api\agents
        target: /srv/smartbox-api/agents
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
