version: '3.8'

services:
  # dind-test2:
  #   image: docker:dind
  #   privileged: true
  #   volumes:
  #     - ../Docking:/flask_app
  #   ports:
  #     - "5000:5000"
  
  flask-app:
    build: 
      context: ./flask_app
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "5000:5000"
    volumes:
      - ./flask_app:/app
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
